language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-apu-codeigniter' ]; then cd .. && eval "mv $currentfolder generator-apu-codeigniter" && cd generator-apu-codeigniter; fi

